# Generated by Django 4.2.6 on 2023-10-13 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avaliablity_days_time',
        ),
    ]
